"""sync models after env fix

Revision ID: 8c25885b97a5
Revises: b24ba9379e63
Create Date: 2025-08-23 13:05:07.253133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c25885b97a5'
down_revision: Union[str, Sequence[str], None] = 'b24ba9379e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    # 1. Находим любую существующую роль, чтобы использовать как "дефолт"
    result = conn.execute(sa.text("SELECT id FROM roles ORDER BY id LIMIT 1"))
    row = result.fetchone()
    if row:
        default_role_id = row[0]
    else:
        # если ролей нет вообще — создаём базовую роль "employee"
        conn.execute(
            sa.text("INSERT INTO roles (name, description) VALUES ('employee', 'default role')")
        )
        default_role_id = conn.execute(
            sa.text("SELECT id FROM roles WHERE name='employee' LIMIT 1")
        ).scalar

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('level')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
